package com.aslmk.greenapitest.client.dto.response;

public record InstanceSettingsResponse(
        String wid,
        String countryInstance,
        String typeAccount,
        String webhookUrl,
        String webhookUrlToken,
        Integer delaySendMessagesMilliseconds,
        String markIncomingMessagesReaded,
        String markIncomingMessagesReadedOnReply,
        String sharedSession,
        String outgoingWebhook,
        String outgoingMessageWebhook,
        String outgoingAPIMessageWebhook,
        String incomingWebhook,
        String deviceWebhook,
        String statusInstanceWebhook,
        String stateWebhook,
        String enableMessagesHistory,
        String keepOnlineStatus,
        String pollMessageWebhook,
        String incomingBlockWebhook,
        String incomingCallWebhook,
        String editedMessageWebhook,
        String deletedMessageWebhook,
        Integer autoTyping,
        String linkPreview,
        String enableLidMode) {}
